name: preflight-project-g11

services:
  db:
    image: postgres:17-alpine
    container_name: pf-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pf-net
volumes:
  pf-data:
networks:
  pf-net: