name: preflight-project-g11

services:
  db:
    image: postgres:17-alpine
    container_name: pf-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pf-data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    networks:
      - pf-net

  backend:
    build: .
    container_name: pf-backend
    ports:
      - ${BACK_END_PORT}:3000
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=pf-db
      - BACK_END_PORT=${BACK_END_PORT}
    command: sh -c "npm run db:migrate && npm run start"
    depends_on:
      - db
    networks:
      - pf-net
volumes:
  pf-data:
networks:
  pf-net: